FROM tensorflow/tensorflow:1.13.2-py3

WORKDIR /home

RUN pip3 install nibabel

CMD ["/bin/bash"]


#sudo docker build -t tf .
#sudo docker run -u $(id -u):$(id -g) -v /home/francesco/Documents/University/UQ/QSMResGAN/:/home -it tf:latest